name: dependabot-automerge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    uses: andrewnordstrom-eng/.github-public/.github/workflows/dependabot-automerge.yml@3c607b1f39d2cf8d6dac6029115ad99964109401
