name: dependabot-automerge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  dependabot-automerge:
    uses: andrewnordstrom-eng/.github-public/.github/workflows/dependabot-automerge.yml@3aaa6ed6e1feef3410e1c5bbdbfa669d43ca39db
